# Generated by Django 4.0.6 on 2022-07-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetuser',
            name='display_name',
            field=models.CharField(default=' ', max_length=32),
            preserve_default=False,
        ),
    ]
