# Generated by Django 4.0.6 on 2022-08-08 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budgetuser_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ta_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='accounts', to='budget.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ta_bucket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='buckets', to='budget.bucket'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ta_payee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='payees', to='budget.payee'),
        ),
    ]
