# Generated by Django 4.0.6 on 2022-10-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_transaction_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='system_bucket',
            field=models.BooleanField(default=False),
        ),
    ]
