# Generated by Django 4.0.6 on 2022-10-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_bucket_system_bucket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='system_bucket',
            new_name='system',
        ),
        migrations.AddField(
            model_name='group',
            name='system',
            field=models.BooleanField(default=False),
        ),
    ]
