# Generated by Django 4.0.6 on 2022-10-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_rename_system_bucket_bucket_system_group_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='system',
        ),
        migrations.RemoveField(
            model_name='group',
            name='system',
        ),
        migrations.AddField(
            model_name='bucket',
            name='on_budget',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bucket',
            name='on_transasction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='on_budget',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='on_transasction',
            field=models.BooleanField(default=True),
        ),
    ]
