# Generated by Django 4.0.6 on 2022-10-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_remove_bucket_system_remove_group_system_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='on_transasction',
            new_name='on_transaction',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='on_transasction',
            new_name='on_transaction',
        ),
    ]
