# Generated by Django 4.0.5 on 2022-10-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_rename_on_transasction_bucket_on_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
