# Generated by Django 4.0.5 on 2022-10-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_transaction_system_transaction_transfer_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cc_debt',
            field=models.BooleanField(default=False),
        ),
    ]
