# Generated by Django 4.0.5 on 2022-10-01 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_transaction_cc_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer_pair',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.transaction'),
        ),
    ]
